import unittest2 as unittest

from collective.externalimageeditor.testing import (
    COLLECTIVE_EXTERNALIMAGEEDITOR_FIXTURE as UNIT_TESTING,
    COLLECTIVE_EXTERNALIMAGEEDITOR_INTEGRATION_TESTING as INTEGRATION_TESTING,
    COLLECTIVE_EXTERNALIMAGEEDITOR_FUNCTIONAL_TESTING as FUNCTIONAL_TESTING,
    COLLECTIVE_EXTERNALIMAGEEDITOR_SELENIUM_TESTING as SELENIUM_TESTING,
)

################################################################################
"""


Lot of files generated by the collective.generic packages  will try to load user defined objects in user specific files.
The final goal is to regenerate easyly the test infrastructure on templates updates without impacting
user-specific test boilerplate.
We do not use paster local commands (insert/update) as it cannot determine witch is specific or not and we prefer to totally
separe generated stuff and what is user specific


"""
################################################################################


class TestCase(unittest.TestCase):
    """We use this base class for all the tests in this package.
    If necessary, we can put common utility or setup code in here.
    """
    layer = UNIT_TESTING


class IntegrationTestCase(TestCase):
    """Integration base TestCase."""
    layer = INTEGRATION_TESTING


class FunctionalTestCase(TestCase):
    """Functionnal base TestCase."""
    layer = FUNCTIONAL_TESTING


class SeleniumTestCase(TestCase):
    """Functionnal base TestCase."""
    layer = SELENIUM_TESTING

# vim:set ft=python:
