from Products.PloneTestCase import PloneTestCase as ptc

from collective.externalimageeditor.testing import layer 

################################################################################
"""


Lot of files generated by the collective.generic packages  will try to load user defined objects in user specific files.
The final goal is to regenerate easyly the test infrastructure on templates updates without impacting
user-specific test boilerplate.
We do not use paster local commands (insert/update) as it cannot determine witch is specific or not and we prefer to totally
separe generated stuff and what is user specific


Think to put "FAILS_ON_UNTESTED_ELEMENT" to True in testing.cfg for production mode or to test very strictly your code!
This will issue errors for untested elements instead of just simple warnings !

"""
################################################################################


class TestCase(ptc.PloneTestCase):
    """We use this base class for all the tests in this package. 
    If necessary, we can put common utility or setup code in here.
    """
    layer = layer

class FunctionalTestCase(ptc.FunctionalTestCase):
    """Functionnal base TestCase."""
    layer = layer

# vim:set ft=python:
